// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

package pb

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type Todos struct {
	TodoList             []*Todo  `protobuf:"bytes,1,rep,name=todoList,proto3" json:"todoList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Todos) Reset()         { *m = Todos{} }
func (m *Todos) String() string { return proto.CompactTextString(m) }
func (*Todos) ProtoMessage()    {}
func (*Todos) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{0}
}

func (m *Todos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todos.Unmarshal(m, b)
}
func (m *Todos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todos.Marshal(b, m, deterministic)
}
func (m *Todos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todos.Merge(m, src)
}
func (m *Todos) XXX_Size() int {
	return xxx_messageInfo_Todos.Size(m)
}
func (m *Todos) XXX_DiscardUnknown() {
	xxx_messageInfo_Todos.DiscardUnknown(m)
}

var xxx_messageInfo_Todos proto.InternalMessageInfo

func (m *Todos) GetTodoList() []*Todo {
	if m != nil {
		return m.TodoList
	}
	return nil
}

// The response message containing the greetings
type Todo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Done                 bool     `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Todo) Reset()         { *m = Todo{} }
func (m *Todo) String() string { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()    {}
func (*Todo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{1}
}

func (m *Todo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todo.Unmarshal(m, b)
}
func (m *Todo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todo.Marshal(b, m, deterministic)
}
func (m *Todo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todo.Merge(m, src)
}
func (m *Todo) XXX_Size() int {
	return xxx_messageInfo_Todo.Size(m)
}
func (m *Todo) XXX_DiscardUnknown() {
	xxx_messageInfo_Todo.DiscardUnknown(m)
}

var xxx_messageInfo_Todo proto.InternalMessageInfo

func (m *Todo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Todo) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Todo) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

type TodoUpdateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Done                 bool     `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoUpdateRequest) Reset()         { *m = TodoUpdateRequest{} }
func (m *TodoUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*TodoUpdateRequest) ProtoMessage()    {}
func (*TodoUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{2}
}

func (m *TodoUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoUpdateRequest.Unmarshal(m, b)
}
func (m *TodoUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoUpdateRequest.Marshal(b, m, deterministic)
}
func (m *TodoUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoUpdateRequest.Merge(m, src)
}
func (m *TodoUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_TodoUpdateRequest.Size(m)
}
func (m *TodoUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TodoUpdateRequest proto.InternalMessageInfo

func (m *TodoUpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TodoUpdateRequest) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

type TodoCreateRequest struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoCreateRequest) Reset()         { *m = TodoCreateRequest{} }
func (m *TodoCreateRequest) String() string { return proto.CompactTextString(m) }
func (*TodoCreateRequest) ProtoMessage()    {}
func (*TodoCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{3}
}

func (m *TodoCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoCreateRequest.Unmarshal(m, b)
}
func (m *TodoCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoCreateRequest.Marshal(b, m, deterministic)
}
func (m *TodoCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoCreateRequest.Merge(m, src)
}
func (m *TodoCreateRequest) XXX_Size() int {
	return xxx_messageInfo_TodoCreateRequest.Size(m)
}
func (m *TodoCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TodoCreateRequest proto.InternalMessageInfo

func (m *TodoCreateRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{4}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Todos)(nil), "Todos")
	proto.RegisterType((*Todo)(nil), "Todo")
	proto.RegisterType((*TodoUpdateRequest)(nil), "TodoUpdateRequest")
	proto.RegisterType((*TodoCreateRequest)(nil), "TodoCreateRequest")
	proto.RegisterType((*Empty)(nil), "Empty")
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor_0e4b95d0c4e09639) }

var fileDescriptor_0e4b95d0c4e09639 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x4b, 0xc4, 0x30,
	0x14, 0xc6, 0x4d, 0xaf, 0x8d, 0xbd, 0x77, 0x20, 0x1a, 0x04, 0x43, 0x51, 0xa8, 0x99, 0xaa, 0x43,
	0x84, 0x3a, 0x38, 0x08, 0x0e, 0x15, 0x71, 0x71, 0xaa, 0xba, 0xb8, 0xdd, 0x99, 0x0c, 0x01, 0x35,
	0xb5, 0x7d, 0x1e, 0x3a, 0xfa, 0x6f, 0x3b, 0x49, 0x5e, 0xf4, 0xa8, 0x78, 0xdb, 0xe3, 0x7b, 0xdf,
	0x2f, 0x5f, 0xbe, 0x07, 0x80, 0xde, 0x78, 0xdd, 0xf5, 0x1e, 0x7d, 0xb1, 0xb7, 0x9c, 0x3f, 0x39,
	0x33, 0x47, 0x7b, 0xf2, 0x3b, 0xc4, 0x85, 0x3a, 0x86, 0xec, 0xce, 0x1b, 0x3f, 0x88, 0x43, 0xc8,
	0x83, 0xff, 0xc6, 0x0d, 0x28, 0x59, 0x39, 0xa9, 0x66, 0x75, 0xa6, 0xc3, 0xa6, 0x5d, 0xc9, 0xea,
	0x02, 0xd2, 0xa0, 0x88, 0x2d, 0x48, 0x9c, 0x91, 0xac, 0x64, 0xd5, 0xb4, 0x4d, 0x9c, 0x11, 0x02,
	0x52, 0xb4, 0xef, 0x28, 0x13, 0x52, 0x68, 0x0e, 0x9a, 0xf1, 0x2f, 0x56, 0x4e, 0x4a, 0x56, 0xe5,
	0x2d, 0xcd, 0xea, 0x0c, 0x76, 0x02, 0x7f, 0xdf, 0x85, 0xfc, 0xd6, 0xbe, 0xbe, 0xd9, 0x01, 0xd7,
	0x3d, 0x46, 0x60, 0x32, 0x02, 0xeb, 0x08, 0x5e, 0xf6, 0x76, 0x04, 0x1e, 0xfc, 0xa4, 0x12, 0xda,
	0x4c, 0xbf, 0x1a, 0xde, 0xa7, 0xdb, 0x4c, 0xee, 0xc6, 0x0f, 0xa8, 0x4d, 0xc8, 0xae, 0x9e, 0x3b,
	0xfc, 0xa8, 0x3f, 0x19, 0xcc, 0x02, 0x7d, 0x6b, 0xfb, 0xa5, 0x7b, 0xb4, 0x62, 0x1f, 0xf2, 0x6b,
	0x8b, 0xb1, 0x34, 0xd7, 0xe4, 0x29, 0x38, 0x55, 0x1d, 0xd4, 0x86, 0x38, 0x02, 0x88, 0x31, 0xd4,
	0x54, 0xe8, 0x7f, 0xb9, 0x45, 0x3c, 0x4b, 0xb4, 0xc6, 0x2a, 0x23, 0xeb, 0x9f, 0x6e, 0x2b, 0x6b,
	0xc3, 0x1f, 0x52, 0x7d, 0xde, 0x2d, 0x16, 0x9c, 0x8e, 0x7e, 0xfa, 0x1d, 0x00, 0x00, 0xff, 0xff,
	0x16, 0xb4, 0x10, 0x68, 0x9b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TodoServiceClient is the client API for TodoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodoServiceClient interface {
	GetTodos(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Todos, error)
	CreateTodo(ctx context.Context, in *TodoCreateRequest, opts ...grpc.CallOption) (*Todo, error)
	UpdateTodo(ctx context.Context, in *TodoUpdateRequest, opts ...grpc.CallOption) (*Todo, error)
}

type todoServiceClient struct {
	cc *grpc.ClientConn
}

func NewTodoServiceClient(cc *grpc.ClientConn) TodoServiceClient {
	return &todoServiceClient{cc}
}

func (c *todoServiceClient) GetTodos(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Todos, error) {
	out := new(Todos)
	err := c.cc.Invoke(ctx, "/TodoService/GetTodos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) CreateTodo(ctx context.Context, in *TodoCreateRequest, opts ...grpc.CallOption) (*Todo, error) {
	out := new(Todo)
	err := c.cc.Invoke(ctx, "/TodoService/CreateTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) UpdateTodo(ctx context.Context, in *TodoUpdateRequest, opts ...grpc.CallOption) (*Todo, error) {
	out := new(Todo)
	err := c.cc.Invoke(ctx, "/TodoService/UpdateTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoServiceServer is the server API for TodoService service.
type TodoServiceServer interface {
	GetTodos(context.Context, *Empty) (*Todos, error)
	CreateTodo(context.Context, *TodoCreateRequest) (*Todo, error)
	UpdateTodo(context.Context, *TodoUpdateRequest) (*Todo, error)
}

func RegisterTodoServiceServer(s *grpc.Server, srv TodoServiceServer) {
	s.RegisterService(&_TodoService_serviceDesc, srv)
}

func _TodoService_GetTodos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).GetTodos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TodoService/GetTodos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).GetTodos(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_CreateTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodoCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).CreateTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TodoService/CreateTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).CreateTodo(ctx, req.(*TodoCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_UpdateTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodoUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).UpdateTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TodoService/UpdateTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).UpdateTodo(ctx, req.(*TodoUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TodoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TodoService",
	HandlerType: (*TodoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTodos",
			Handler:    _TodoService_GetTodos_Handler,
		},
		{
			MethodName: "CreateTodo",
			Handler:    _TodoService_CreateTodo_Handler,
		},
		{
			MethodName: "UpdateTodo",
			Handler:    _TodoService_UpdateTodo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo.proto",
}
