// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: todo.proto

package pb

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Todos) Validate() error {
	for _, item := range this.TodoList {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("TodoList", err)
			}
		}
	}
	return nil
}
func (this *Todo) Validate() error {
	return nil
}
func (this *TodoRequest) Validate() error {
	if this.Text == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Text", fmt.Errorf(`value '%v' must not be an empty string`, this.Text))
	}
	if !(len(this.Text) < 20) {
		return github_com_mwitkow_go_proto_validators.FieldError("Text", fmt.Errorf(`value '%v' must have a length smaller than '20'`, this.Text))
	}
	return nil
}
func (this *Empty) Validate() error {
	return nil
}
